version: "3.8"

services:
  proxy:
    environment:
    - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME?Create basic auth username for admin service}
    - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD?Create basic auth password for admin service}
    networks:
    - net
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M
  api:
    networks:
    - net
  admin:
    networks:
    - net
  front:
    networks:
    - net
  front-teacher:
    networks:
    - net
  executor:
    networks:
    - net
  rabbitmq:
    networks:
    - net

networks:
  net:
    driver: overlay
