version: "3.8"

services:
  proxy:
    image: rtuitlab/olympiad-proxy
    logging:
      driver: "json-file"
      options:
          max-size: "200k"
          max-file: "10"
  front-teacher:
    image: rtuitlab/olympiad-front-teacher
    logging:
      driver: "json-file"
      options:
          max-size: "200k"
          max-file: "10"