version: "3.8"

services:
  proxy:
    environment:
    - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME?Create basic auth username for admin service}
    - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD?Create basic auth password for admin service}
    networks:
    - net
  api:
    networks:
    - net
  admin:
    networks:
    - net
  front:
    networks:
    - net
  executor:
    networks:
    - net
  rabbitmq:
    networks:
    - net

networks:
  net:
    driver: overlay
