version: "3.8"

services:
  proxy:
    image: rtuitlab/olympiad-proxy
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M
    logging:
      driver: "json-file"
      options:
          max-size: "200k"
          max-file: "10"