version: "3.8"

services:
  proxy:
    build: Proxy
    environment:
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=VeryStrongPassword1
    ports:
      - 5500:5500
    restart: on-failure
